### PR TITLE
Switch to CC BY-SA

### PR DESCRIPTION
**Pull request by jeremy-rifkin**
We're changing the license of the contents here to be CC BY-SA. We have discussed this with contributors and would appreciate approval on this PR from:

- [x] @michael-kenzel
- [x] @deqyra 
- [x] @Eisenwave 
- [x] @SlackingSleeper 
- [x] @Phytolizer 
- [x] @Yinsei 
- [x] @mcmlevi 
- [x] @JaiganeshKumaran 
- [x] @sarvl

### CODE REVIEW

**Comment by michael-kenzel** [comment]
[x] @michael-kenzel

**Comment by Eisenwave** [comment]
* [x]  @Eisenwave

**Comment by deqyra** [comment]
[x] @deqyra

**Comment by SlackingSleeper** [comment]
* [x]  @SlackingSleeper

**Comment by Phytolizer** [comment]
- [x] @Phytolizer

**Comment by mcmlevi** [comment]
[x]

**Comment by sarvl** [comment]
- [x] @sarvl

**Comment by JaiganeshKumaran** [comment]
[x] @JaiganeshKumaran

**Pull request merged**
